---
# file: roles/galera/tasks/configurations/Debian.yml
- name: Set root password for localhost (Debian family)
  mysql_user:
    name=root
    password="{{ mariadb_root_password }}"
    host={{ item }}
    state=present
    with_items:
      - "{{ ansible_fqdn }}"
      - 127.0.0.1
      - localhost
  when: inventory_hostname == master

- name: Configuring root access for Ansible (Debian family)
  file:
    src=/etc/mysql/debian.cnf
    dest=/root/.my.cnf
    state=link
    force=yes

- name: Set debian-sys-maint password for localhost (Debian family)
  mysql_user:
    name="debian-sys-maint"
    password="{{ mariadb_maintenance_password }}"
    host=localhost
    state=present
  when: inventory_hostname == master

# Note: We doubl update the password, as it seems on ubuntu and maridb 10.1.14 
# it doesnt work correctly with above command
- name: Update MySQL debian-sys-maint password for localhost account.
  shell: >
    mysql -u root -NBe
    'SET PASSWORD FOR "debian-sys-maint"@"localhost" = PASSWORD("{{ mariadb_maintenance_password }}");'
  with_items: "{{ mysql_root_hosts.stdout_lines }}"
  when: inventory_hostname == master  

- name: Removing old /root/.my.cnf file (Debian family)
  file:
    path=/root/.my.cnf
    state=absent

- name: Creating the final /root/.my.cnf file (Debian family)
  template:
    src=root/my.cnf.debian.j2
    dest=/root/.my.cnf
    mode=0640

- name: Configuring Galera cluster (1/3) (Debian family)
  template:
    src=etc/mysql/my.cnf.j2
    dest=/etc/mysql/my.cnf

- name: Configuring Galera cluster (2/3) (Debian family)
  template:
    src=etc/mysql/conf.d/galera.cnf.j2
    dest=/etc/mysql/conf.d/galera.cnf

- name: Configuring Galera cluster (3/3) (Debian family)
  template:
    src=etc/mysql/debian.cnf.j2
    dest=/etc/mysql/debian.cnf
    mode=0600

- name: Deleting mariadb.cnf config file (Debian family)
  file:
    path=/etc/mysql/conf.d/mariadb.cnf
    state=absent
