---
# file: roles/galera/tasks/secure.yml
- name: Removing test default database
  mysql_db:
    name: test
    state: absent
  when: inventory_hostname == master

- name: Disabling remote access for root
  mysql_user:
    name: root
    host: "{{ item }}"
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - '::1'
  when: inventory_hostname == master

- name: Disabling anonymous access
  mysql_user:
    name: ""
    state: absent
  when: inventory_hostname == master

- name: Get list of hosts for the root user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mysql_root_hosts
  changed_when: false
  when: inventory_hostname == master

# Note: We do not use mysql_user for this operation, as it doesn't always update
# the root password correctly. See: https://goo.gl/MSOejW
- name: Update MySQL root password for localhost root account.
  shell: >
    mysql -u root -NBe
    'SET PASSWORD FOR "root"@"{{ item }}" = PASSWORD("{{ mariadb_root_password }}");'
  with_items: "{{ mysql_root_hosts.stdout_lines }}"
  when: inventory_hostname == master