---
# file: roles/galera/tasks/repos/Ubuntu.yml
- name: Install MariaDB Galera repository (Debian)
  apt_repository:
    repo='deb http://mariadb.mirror.iweb.com/repo/10.1/ubuntu main main'
    filename='mariadb'
    state=present
    update_cache=true
- apt_key:
    keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
    state=present

- name: Install Percona repository (Debian)
  apt_repository:
    repo='deb http://repo.percona.com/apt trusty main'
    filename='percona'
    state=present
    update_cache=true
- apt_key:
    keyserver=keys.gnupg.net id=1C4CBDCDCD2EFD2A
    state=present
